### ISSUE TITLE
What are the names for each class in 13-label version of SUNRGBD

### ISSUE THREAD

**Issue by claudehang** [ankurhanda/sunrgbd-meta-data#1]
Where this meta data could be found? Many thanks!

**Comment by ankurhanda** [comment]
You can check my SceneNet as well as SceneNet RGB-D paper. This repo does provide train and test 13 class labels and match it against the papers. Once you have done it you can perhaps create a PR and I will merge it to the repo. Thanks.

**Comment by irfanICMLL** [comment]
What is the label 0 mean in the class37? The background class or the 'ignore' class?

**Comment by ankurhanda** [comment]
ignore

**Comment by irfanICMLL** [comment]
Thanks

**Comment by loveis98** [comment]
I loaded sunrgbd_train_test_labels.tar.gz, but I didn't understand, how the labeled image pixels correspond to the classes? F.e., seg[0][0] gives me 0.06666667 -  float value. Would you help me?

**Comment by ankurhanda** [comment]
Are you reading them into float variables directly? You should only see integers.

**Comment by loveis98** [comment]
I read images by **matplotlib.image.mpimg.imread**

**Comment by ankurhanda** [comment]
I did this 
```ankurhanda@ankurs-MacBook-Pro.local:~/Downloads$ python3
Python 3.6.4 (default, Mar  9 2018, 23:15:12) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import misc
>>> A = misc.imread('img-010333.png')
>>> A
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 5, 5, ..., 5, 5, 5],
       [5, 5, 5, ..., 0, 0, 0],
       [5, 5, 5, ..., 0, 0, 0]], dtype=uint8)
>>> import numpy as np
>>> np.amax(A)
7
```

**Comment by loveis98** [comment]
ok, thanks:)
