### ISSUE TITLE
physical meaning of 3D annotation parameters 

### ISSUE THREAD

**Issue by betterze** [ankurhanda/sunrgbd-meta-data#2]
Dear Ankur,

I am a PhD student from Hebrew University, I am very interested in <SUN RGB-D: A RGB-D scene understanding benchmark suite>.

In the 3D annotation (SUNRGBMeta -> groundtruth3DBB), there are a few parameters about 3D structure, which include basis, coeffs, centroid and orientation. Could you tell me the physical meaning of these parameters? Or where I can find the description?

Thank you very much for your help. I really appreciate it.

Best regards，

Alex

**Comment by betterze** [comment]
Specifically, in orientation, there are 3 parameters, with min -1 and max 1. Could you tell me what these parameters mean?

**Comment by betterze** [comment]
any reply?

**Comment by ankurhanda** [comment]
I don't remember much about these parameters because I didn't use them but I think the description should be on the SUN RGB-D dataset: http://rgbd.cs.princeton.edu/challenge.html

**Comment by betterze** [comment]
Thanks, I know how to solve the problem now.

**Comment by Crispus1119** [comment]
@betterze hey! I am also confused about that. Can you tell me what those annotation meaning ? thanks!!!!

**Comment by betterze** [comment]
@Crispus1119 Sorry, they did not reply me. I still dont know what those annotation means.
