### ISSUE TITLE
SUNRGB-D semantic segmentation label

### ISSUE THREAD

**Issue by betterze** [ankurhanda/sunrgbd-meta-data#3]
Dear Ankur, 

I am a PhD student from Hebrew University, I am very interested in your work. Thank you very much for your effort. I meet a problem when using this dataset, could you help me with it?

When I use demo.m in SUNRGBDtoolbox to visualize the semantic segmentation results, I set ImageId=9, the image with bounding box and 37 class semantic segmentation (anno2d.seglabel) are in the following.

![box](https://user-images.githubusercontent.com/8336718/57072819-b4518f80-6ce7-11e9-8e91-ab8d65092e04.jpg)
![image](https://user-images.githubusercontent.com/8336718/57072821-b582bc80-6ce7-11e9-8595-91d7c982a4f4.png)

As we can see from the graphs, the bounding box annotation could recognize the 'bed'.  But when we use 'impixel' to show the pixel value of semantic map as indicated by 'start' mark , the value it returned is '0,0,0'. According to seg37list, 0 refers to unlabeled, 4 refers to bed, which means the label of this pixel is 'unlabeled' rather than 'bed'. However, we can clearly see this is a bed region, and bounding box annotation also recognize it. I also try other pixels in bed region, they all return 0. So this is a label error in semantic map, is my interpretation correct? Could you tell me why this is happen? Am I doing anything wrong? I also find this phenomenon is some other images. 

Thank you very much for your help.

Best Wishes,

Alex

**Comment by betterze** [comment]
And in ImageId=3002. In bounding box annotation, the label is desk. But in semantic segmentation, the label is table. They are not consistent.

**Comment by betterze** [comment]
any reply?

**Comment by ankurhanda** [comment]
It may be worth checking the depth image to find out if there's any depth in that region otherwise labels won't make sense.

**Comment by betterze** [comment]
Thanks, I know how to solve the problem now.

**Comment by irfanICMLL** [comment]
> It may be worth checking the depth image to find out if there's any depth in that region otherwise labels won't make sense.

You mean if the region has an invalid depth, the region will be labeled as 'unlabeled'?

**Comment by ankurhanda** [comment]
Yeah!
