### ISSUE TITLE
Does this contain all train images?

### ISSUE THREAD

**Issue by Guptajakala** [ankurhanda/sunrgbd-meta-data#4]
The orignal dataset claims they have much more than the ~5000 images here.
Is this repo missing anything?

**Comment by ankurhanda** [comment]
![images](https://user-images.githubusercontent.com/686480/58922030-0e31e480-86ee-11e9-8f9d-ccc55431d477.png)

They are here.

**Comment by Guptajakala** [comment]
@ankurhanda Yes, that's what I'm asking.
Since here there is only ~5000 training images.
But if you check the original dataset, they have much much more than this.

**Comment by ankurhanda** [comment]
When I created this repo they had only 5285 images for SUN RGB-D dataset. These are the images for which they had annotations. I don't use this dataset anymore so I haven't checked back and updated it.

**Comment by Guptajakala** [comment]
@Guptajakala OK, thanks for the info!

**Comment by Guptajakala** [comment]
@ankurhanda 
Sorry, my bad. I was counting both training and test images from original SUNRGBD.
This repo indeed contains all the data.
Thanks for sharing this awesome work!
