### ISSUE TITLE
Where is sunrgbd_train_test_labels.tar.gz?

### ISSUE THREAD

**Issue by charlesCXK** [ankurhanda/sunrgbd-meta-data#5]
Hi! Thank you for your sharing. I have a question that I can't find **_sunrgbd_train_test_labels.tar.gz_**. Could you upload it? Thank you very much!

**Comment by ankurhanda** [comment]
It is in the root directory. You can find everything that's mentioned or talked about in the readme in the root folder......
 
<img width="1000" alt="Screenshot 2019-09-01 at 07 35 33" src="https://user-images.githubusercontent.com/686480/64078063-3bf5dd80-cc8b-11e9-8c8f-0ebacbef41b9.png">

**Comment by charlesCXK** [comment]
> It is in the root directory. You can find everything that's mentioned or talked about in the readme in the root folder......
> 
> <img alt="Screenshot 2019-09-01 at 07 35 33" width="1000" src="https://user-images.githubusercontent.com/686480/64078063-3bf5dd80-cc8b-11e9-8c8f-0ebacbef41b9.png">

Sorry..... I searched it in this repo but didn't find it. There must be something wrong that time. Now I see it, thanks!
