### ISSUE TITLE
visualize the labels

### ISSUE THREAD

**Issue by yuxiangsun** [ankurhanda/sunrgbd-meta-data#6]
Do your labels contain 38 classes (including the unlabeled background)?
What are the class names for the numbers (0-37)?
Could you provide the color palette for visualization?

**Comment by ankurhanda** [comment]
it's on the front page...
<img width="886" alt="Screenshot 2019-09-05 at 07 40 51" src="https://user-images.githubusercontent.com/686480/64352252-8d1a1000-cfb0-11e9-8f9c-036286325cb5.png">

**Comment by yuxiangsun** [comment]
Does value 0 correspond to the unlabelled background? You just mention 37 classes on the page. 

I just want to make sure whether there are total 38 classes including the background, and whether 0 is the background.

**Comment by ankurhanda** [comment]
I don't use 0 for my case (so that's 37) but you can!

**Comment by yuxiangsun** [comment]
Sorry, maybe my question is not clear.

In your provided sunrgbd_train_test_labels.tar.gz, many label images have pixels with value 0. 

I want to ask whether these 0 value pixels represent the unlabelled background. 

Thank you so much.
